export const SIDO_LIST = [{ id: 0, name: '' }];
export const CATEGORY_LIST = [
  { id: 0, name: '모두 보기' },
  { id: 1, name: '국회운영' },
  { id: 2, name: '법제사법' },
  { id: 3, name: '교육' },
  { id: 4, name: '국방' },
  { id: 5, name: '농림축산식품해양수산' },
  { id: 6, name: '과학기술정보방송통신' },
  { id: 7, name: '문화체육관광' },
  { id: 8, name: '국토교통' },
  { id: 9, name: '기획재정' },
  { id: 10, name: '외교통일' },
  { id: 11, name: '환경노동' },
  { id: 12, name: '보건' },
  { id: 13, name: '행정안전' },
  { id: 14, name: '정무' },
  { id: 15, name: '산업통상자원중소벤처기업' },
  { id: 16, name: '정보' },
  { id: 17, name: '여성가족' },
];
